### ISSUE TITLE
artikel tidak bisa tampil

### ISSUE THREAD

**Issue by DamesDamai** [kusmantopratama/OpenSID-Djuara#1]
kenapa tema djuara ini tidak bisa menampilkan artikel

**Comment by tamapratamaongit** [comment]
@DamesDamai  artikel yang dimana pak ?

**Comment by tamapratamaongit** [comment]
coba update ke versi terbaru dan lakukan migrasi db @DamesDamai

**Comment by tamapratamaongit** [comment]
update opensid nya pak dan lakukan migrasi db @DamesDamai
